name: build to github

on:
  push:
    branches: [main, develop] # 해당 branch에 push 되었을 경우

jobs:
  github-build-and-push: # Jon 이름
    runs-on: ubuntu-22.04

    # 실행 스텝 지정
    # https://github.com/marketplace/actions/build-with-gradle
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # java version 지정
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Build
      - name: Build with Gradle
        run: ./gradlew clean build


      # https://github.com/marketplace/actions/build-and-push-docker-images
      # 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 관련 설적 적용
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build 및 Push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: . # 지정하지 않으면 기본적으로 현재 디렉토리가 빌드 컨텍스트로 사용됩니다.
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_TAG_NAME }}:latest

  deploy-to-ec2:
    needs: github-build-and-push
    runs-on: ubuntu-22.04
    # https://github.com/marketplace/actions/ssh-remote-commands
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            CONTAINER_ID=$(sudo docker ps -q --filter "publish=8080-8080")

            if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi

            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_TAG_NAME }}:latest
            sudo docker run -d -p 8080:8080 \
                -e DB_URL=${{ secrets.DB_URL }} \
                -e DB_USER=${{secrets.DB_USER}} \
                -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
                -e DB_HOST=${{secrets.DB_HOST}} \
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_TAG_NAME }}:latest